<?php
$_['heading_title'] = 'SEO Autogenerate';
$_['text_success'] = 'are Autogenerated Successfully!';
$_['text_module'] = 'Modules';
$_['back'] = 'Back';
$_['warning_clear'] = 'Warning: this will clear all previous SEO Keywords!';
$_['warning_clear_tags'] = 'Warning: this will clear all previous tags!';
$_['categories'] = 'Categories:';
$_['mall_categories'] = 'Mall Categories URL Keyword';
$_['information_pages_mall'] = 'Information Pages URL Keyword';
$_['information_pages'] = 'Information Pages:';
$_['products'] = 'Products:';
$_['generate'] = 'Generate';
$_['error_permission'] = 'Warning: You do not have permission to use seo module!';
$_['manufacturers'] = 'Manufacturers:';
$_['template'] = 'Template:';
$_['available_category_tags'] = 'Available tags: [category_name]';
$_['available_information_pages_tags'] = 'Available tags: [information_page_title]';
$_['available_product_tags'] = 'Available tags: [product_name], [model_name], [manufacturer_name]';
$_['available_manufacturer_tags'] = 'Available tags: [manufacturer_name]';
$_['available_meta_tags'] = 'Available tags: [product_name], [model_name], [manufaturer_name], [categories_names]';
$_['available_tags_tags'] = 'Available tags: [product_name], [model_name], [manufaturer_name], [categories_names]';
$_['meta_keywords'] = 'Meta keywords:';
$_['add_from_yahoo'] = 'Add terms from Yahoo! Term extraction service using the product description.';
$_['your_yahoo_id'] = 'Your Yahoo! Application ID';
$_['get_yahoo_id'] = 'Grab one <a href="http://developer.yahoo.com/wsregapp/" target="_blank">here</a>. Choose generic authentication method.';
$_['enter_yahoo_id'] = 'Please enter your Yahoo! Application ID if you want to use the Yahoo! Term extraction service!';
$_['curl_not_enabled'] = 'Please enable the cURL extension if you want to use the Yahoo! Term extraction service.';
$_['tags'] = 'Tags';
$_['source_language'] = 'Source language:';

// Text
$_['text_entity'] = 'Entity';
$_['text_description'] = 'Description';
$_['text_pattern'] = 'Pattern';
$_['text_action'] = 'Action';
$_['text_products'] = 'Products';
$_['text_categories'] = 'Categories';
$_['text_manufacturers'] = 'Manufacurers';
$_['text_information_pages'] = 'Information Pages';
$_['text_url_keyword'] = 'URL Keyword';
$_['text_title'] = 'Title';
$_['text_meta_keywords'] = 'Meta Keywords';
$_['text_meta_description'] = 'Meta Description';
$_['text_tags'] = 'Tags';
$_['text_image_name'] = 'Image Name';

$_['autogenerate_help'] = 'Note: An action will clear all previous database entries!';

//Dynamic success
$_['product_url_keyword'] = 'Product url Keywords';
$_['product_title'] = 'Products Title';
$_['product_meta_keywords'] = 'Product meta Keywords';
$_['product_meta_description'] = 'Product meta Descriptions';
$_['product_tags'] = 'Product Tags';
$_['product_image_name'] = 'Product Image Names';
$_['category_url_keyword'] = 'Categories url Keywords';
$_['category_meta_description'] = 'Categories meta Description';
$_['category_meta_keywords'] = 'Categories meta keywords';
$_['category_title'] = 'Categories Title';
$_['manufacturer_url_keyword'] = 'Manufacturer Url Keywords';
$_['information_page_url_keyword'] = 'Information pages Url Keywords';
$_['information_page_title'] = 'Information pages Titles';

// Dynamic description
$_['user_defined_text'] = '	<br>If you wish to add customized text write the text after of before the tags.<br>
							For best results seperate you text and predefined tags with a hyphen(-).<br>
							Example: [tag], -your text-, [tag]';

$_['user_defined_text_meta'] = 		'<br>If you wish to add customized text write the text after of before the tags.<br>
								 	For best results seperate you text and predefined tags with a comma(,).<br>
									Example: [tag], your text, [tag]';

$_['dymanic_seo_description']	= '	This will generate SEO URL KEYWORD for %s from relevant words.<br>
								<b>Available tags for pattern: </b>%s<br>%s';

$_['dymanic_title']	= '	This will generate TITLE for %s from relevant words.<br>
								<b>Available tags for pattern: </b>%s<br>%s';
								
$_['dymanic_keywords_description']	= '	This will generate META KEYWORDS for %s from relevant words.<br>
								<b>Available tags for pattern: </b>%s<br>%s';

$_['dymanic_description']	= '	This will generate META DESCRIPTION for %s from relevant words.<br>
								<b>Available tags for pattern: </b>%s<br>%s';

$_['dymanic_tags']	= 	' This will generate TAGS for %s from relevant words.<br>
						  <b>Available tags for pattern: </b>%s<br>%s';

$_['dymanic_image_description']	= '	This will generate and replace IMAGE NAME for %s from relevant words.<br>
									<b>Available tags for pattern: </b>%s<br>%s';

// Note
$_['note_meta_description'] = '<b>Note:</b> First 120 characters of the %s description will be used to generate meta description.';
